#!/usr/bin/env python3
"""
power_smoother_13.py  (noise isolation + affinity rewrite)
====================
Background daemon v13: monitors CPU package power via RAPL and smooths V-dips.

Three architectural improvements over v12
------------------------------------------
1. Rolling-Window Derivative (low-pass filter)
   v12 computed dP/dt from two consecutive 2 ms samples.  A single noisy RAPL
   MSR read can produce a spurious 10 000+ W/s spike and false-trigger a ramp.
   v13 keeps a collections.deque of the last DERIV_WINDOW_SECS (50 ms) of
   readings and computes the derivative from the oldest to newest sample in that
   window.  This acts as a low-pass filter: genuine sharp drops survive; RAPL
   quantisation noise averages out.

2. CPU Affinity (core isolation)
   With 16 background workers + 8 benchmark tasks + the daemon main loop all
   competing for the same cores, the Linux scheduler thrashes and the RAPL
   registers see cross-contamination from context switches.
   v13 calls os.sched_setaffinity() to pin the daemon main process and every
   worker exclusively to the upper half of available CPU cores, leaving the
   lower half entirely clean for the benchmark workload.

3. Worker Local Read Stalling (cache-coherency relief)
   mp.Value is backed by shared memory with a lock; every read is a cache-line
   transfer on the interconnect.  With 16 workers polling every 10 ms that is
   1 600 lock acquisitions per second in steady state.
   v13 workers cache their iteration target locally:
     • IDLE path  : re-read once after every IDLE_BACKOFF_SECS sleep (100 ms).
     • ACTIVE path: re-read only every ACTIVE_READ_INTERVAL windows (50 ms),
                    reducing steady-state shared-memory traffic by 5×.

Fixed experimental parameters
------------------------------
  detection threshold  : -3000 W/s  (over 50 ms window)
  back-off threshold   :  +1500 W/s  (power rise during ramp → abort)
  ramp-down window     :  6.0 s (linear watts decay, may abort early)
  cooldown             :  2.0 s after every event before re-arming
  window size          :  10 ms (must match calibrate_power.py WINDOW_SEC)

Run as root in the background:
  sudo python3 power_smoother_13.py &

Kill cleanly when done:
  sudo kill $(cat /tmp/smoother13.pid)

Output files
------------
  power_samples_13.csv  — full RAPL trace (written on exit)
  events_13.csv         — one row per event (written in real time)
"""

from __future__ import annotations

import collections
import csv
import math
import multiprocessing as mp
import os
import signal
import time

from rapl_reader import RaplMonitor

# ── Calibration lookup (generated by calibrate_power.py) ─────────────────────
try:
    from calib_lookup import watts_to_iters as _calib_watts_to_iters
    _CALIB_AVAILABLE = True
except ImportError:
    _CALIB_AVAILABLE = False

# ── CPU topology ──────────────────────────────────────────────────────────────
_N_CPUS      = os.cpu_count() or 2
# Upper half of cores: reserved for daemon + workers
WORKER_CORES = set(range(_N_CPUS // 2, _N_CPUS))
# Lower half: left entirely free for the benchmark workload
BENCH_CORES  = set(range(0, _N_CPUS // 2))
N_WORKERS    = min(len(WORKER_CORES), 16)

# ── Fixed experimental parameters ────────────────────────────────────────────
WINDOW_SEC         = 0.010    # s    10 ms duty-cycle window — must match calibration
DERIV_WINDOW_SECS  = 0.050    # s    rolling window for dP/dt low-pass filter
DERIV_MIN_SAMPLES  = 5        # min samples in deriv window before arming trigger
DERIV_THRESHOLD    = -3000.0  # W/s  drop trigger
BACKOFF_THRESHOLD  = +1500.0  # W/s  power rise during ramp → abort immediately
RAMPDOWN_SECS      = 6.0      # s    max ramp duration
DETECT_POLL_SECS   = 0.002    # s    2 ms poll in IDLE (feeds rolling window)
CTRL_STEP          = 0.25     # s    iteration update interval during ramp
CALIB_WINDOW       = 0.4      # s    RAPL snapshot window used for event logging
COOLDOWN_SECS      = 2.0      # s    quiet period after each event before re-arm

BASELINE_FALLBACK  = 400.0    # W    used when history is too short
BASELINE_WINDOW    = 60.0     # s    look-back window for idle power estimation
BASELINE_MARGIN    = 20.0     # W    abort ramp early if within this of baseline

IDLE_FLOOR_ITERS   = 0        # iteration target during IDLE/COOLDOWN
IDLE_BACKOFF_SECS  = 0.1      # s    worker sleep when at idle floor
ACTIVE_READ_INTERVAL = 5      # re-read shared iters only every N active windows
STARTUP_GRACE_SECS = 2.0      # s    ignore derivative triggers on startup

FALLBACK_MAX_ITERS = 50_000   # ceiling without calibration (overruns window = full blast)

PID_FILE    = "/tmp/smoother13.pid"
SAMPLES_CSV = "power_samples_13.csv"
EVENTS_CSV  = "events_13.csv"

EVENTS_FIELDS = [
    "event_num", "detected_at_s", "rate_w_per_s",
    "power_at_detect_w", "baseline_w", "handoff_w",
    "initial_iters", "final_w", "ramp_duration_s", "abort_reason",
]


# ── Worker with affinity pinning + local read stalling ───────────────────────

def _worker_fn(
    iters_per_window: "mp.Value[int]",
    stop_evt: mp.Event,
    worker_cores: set[int],
) -> None:
    """
    Pinned to worker_cores via sched_setaffinity on startup.

    Caches the iteration target locally (local_iters) and re-reads the shared
    mp.Value only at defined intervals to reduce cache-coherency traffic:
      • Idle path  : sleep IDLE_BACKOFF_SECS, then re-read once.
      • Active path: re-read every ACTIVE_READ_INTERVAL windows (≈ 50 ms).
    """
    try:
        os.sched_setaffinity(0, worker_cores)
    except (AttributeError, OSError):
        pass   # not available on all platforms / kernels

    x            = 1.000001
    local_iters  = IDLE_FLOOR_ITERS
    active_pass  = 0

    while not stop_evt.is_set():
        if local_iters <= IDLE_FLOOR_ITERS:
            time.sleep(IDLE_BACKOFF_SECS)
            local_iters = iters_per_window.value   # re-read after each backoff
            active_pass = 0
            continue

        # Active: re-read shared value every ACTIVE_READ_INTERVAL windows
        active_pass += 1
        if active_pass >= ACTIVE_READ_INTERVAL:
            local_iters = iters_per_window.value
            active_pass = 0

        t_start = time.monotonic()
        for _ in range(local_iters):
            x = math.sqrt(x * x + 1.0) - math.sqrt(x * x - 1.0 + 1e-15)
            x = math.sin(x) * math.cos(x) + math.exp(-x * x) + 1.0
        remaining = WINDOW_SEC - (time.monotonic() - t_start)
        if remaining > 0.0005:
            time.sleep(remaining)


# ── Baseline estimator ────────────────────────────────────────────────────────

def _estimate_baseline(
    history: "collections.deque[tuple[float, float]]",
    now: float,
) -> float:
    cutoff  = now - BASELINE_WINDOW
    samples = sorted(w for t, w in history if t >= cutoff)
    if len(samples) < 20:
        return BASELINE_FALLBACK
    return samples[max(0, len(samples) // 10)]


# ── CSV helpers ───────────────────────────────────────────────────────────────

def _write_samples(samples: list[tuple[float, float]]) -> None:
    with open(SAMPLES_CSV, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["timestamp_s", "power_w"])
        w.writerows(samples)
    print(f"[Saved] {len(samples)} samples → {SAMPLES_CSV}")


def _append_event(row: dict) -> None:
    exists = os.path.exists(EVENTS_CSV)
    with open(EVENTS_CSV, "a", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=EVENTS_FIELDS)
        if not exists:
            writer.writeheader()
        writer.writerow(row)


# ── Signal handler ────────────────────────────────────────────────────────────

_running = True


def _on_signal(sig: int, frame) -> None:  # type: ignore[type-arg]
    global _running
    _running = False


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    global _running

    if os.geteuid() != 0:
        print("Error: RAPL requires root.  Run: sudo python3 power_smoother_13.py")
        raise SystemExit(1)

    signal.signal(signal.SIGINT,  _on_signal)
    signal.signal(signal.SIGTERM, _on_signal)

    with open(PID_FILE, "w") as f:
        f.write(f"{os.getpid()}\n")

    # Pin the daemon's main loop to the worker cores so it does not compete
    # with benchmark tasks on the lower-half cores.
    try:
        os.sched_setaffinity(0, WORKER_CORES)
        print(f"[Daemon] Main process pinned to cores {sorted(WORKER_CORES)}")
        print(f"[Daemon] Benchmark cores reserved  : {sorted(BENCH_CORES)}")
    except (AttributeError, OSError) as e:
        print(f"[Daemon] WARNING: sched_setaffinity unavailable ({e}) — no pinning")

    if not _CALIB_AVAILABLE:
        print("[Daemon] WARNING: calib_lookup.py not found — ramp will use a linear "
              f"iteration fallback (ceiling={FALLBACK_MAX_ITERS:,} iters/window).  "
              "Run calibrate_power.py first for accurate power targeting.")

    # ── Spawn workers ─────────────────────────────────────────────────────────
    iters_per_window: "mp.Value[int]" = mp.Value("i", IDLE_FLOOR_ITERS)
    stop_evt = mp.Event()

    workers = [
        mp.Process(
            target=_worker_fn,
            args=(iters_per_window, stop_evt, WORKER_CORES),
            daemon=True,
        )
        for _ in range(N_WORKERS)
    ]
    for w in workers:
        w.start()
    pids = [w.pid for w in workers]

    rapl = RaplMonitor(interval=0.05)
    rapl.start()
    time.sleep(0.2)

    if os.path.exists(EVENTS_CSV):
        os.remove(EVENTS_CSV)

    calib_note = "calib_lookup" if _CALIB_AVAILABLE else f"fallback ({FALLBACK_MAX_ITERS:,} iters max)"
    print(f"[Daemon] v13  drop={DERIV_THRESHOLD:.0f} W/s (over {DERIV_WINDOW_SECS*1000:.0f} ms window)  "
          f"backoff={BACKOFF_THRESHOLD:+.0f} W/s  ramp={RAMPDOWN_SECS:.1f} s  "
          f"cooldown={COOLDOWN_SECS:.1f} s")
    print(f"[Daemon] {N_WORKERS} workers  cores={sorted(WORKER_CORES)}  iters={calib_note}")
    print(f"[Daemon] PID {os.getpid()} → {PID_FILE}  PIDs: {pids}\n")

    # ── State machine ─────────────────────────────────────────────────────────
    #
    #   IDLE ──(drop detected)──► RAMPDOWN ──(done/backoff/baseline)──► COOLDOWN
    #    ▲                                                                    │
    #    └─────────────────────────────────────────────────────────────────────┘
    #
    state     = "IDLE"
    t_origin  = time.monotonic()
    event_num = 0

    # Long-window history for baseline percentile estimation
    history: collections.deque[tuple[float, float]] = collections.deque()

    # Short-window deque for rolling dP/dt — replaces prev_w/prev_t
    deriv_buf: collections.deque[tuple[float, float]] = collections.deque()

    ramp_start  = 0.0
    ramp_last_w: float | None = None
    ramp_last_t: float | None = None

    event_detect_t      = 0.0
    event_detect_w      = 0.0
    event_rate          = 0.0
    event_initial_iters = 0
    handoff_w           = 0.0
    baseline_w          = BASELINE_FALLBACK

    while _running:
        t_now = time.monotonic()
        w_now = rapl.current_watts

        # ── IDLE ──────────────────────────────────────────────────────────────
        # Workers run at IDLE_FLOOR_ITERS.  Derivative detection is ONLY here.
        # dP/dt is computed from the oldest→newest sample in deriv_buf (50 ms
        # rolling window) to filter out RAPL quantisation noise.
        if state == "IDLE":
            history.append((t_now, w_now))
            while history and t_now - history[0][0] > BASELINE_WINDOW:
                history.popleft()

            deriv_buf.append((t_now, w_now))
            while deriv_buf and t_now - deriv_buf[0][0] > DERIV_WINDOW_SECS:
                deriv_buf.popleft()

            armed = (t_now - t_origin) >= STARTUP_GRACE_SECS
            if armed and len(deriv_buf) >= DERIV_MIN_SAMPLES:
                t_old, w_old = deriv_buf[0]
                t_new, w_new = deriv_buf[-1]
                dt = t_new - t_old
                if dt > 0:
                    rate = (w_new - w_old) / dt
                    if rate <= DERIV_THRESHOLD:
                        baseline_w = _estimate_baseline(history, t_now)
                        handoff_w  = rapl.snapshot_watts(window=CALIB_WINDOW)

                        if _CALIB_AVAILABLE:
                            initial_iters = _calib_watts_to_iters(handoff_w)
                        else:
                            initial_iters = FALLBACK_MAX_ITERS

                        iters_per_window.value = initial_iters

                        ramp_start     = time.monotonic()
                        event_num     += 1
                        event_detect_t = t_now - t_origin
                        event_detect_w = w_now
                        event_rate     = rate
                        event_initial_iters = initial_iters

                        print(f"[Event {event_num}] t={event_detect_t:.3f} s  "
                              f"dP/dt={rate:+.0f} W/s  power={w_now:.1f} W  "
                              f"baseline≈{baseline_w:.1f} W  handoff={handoff_w:.1f} W  "
                              f"init_iters={initial_iters:,}  → workers scaling up")

                        deriv_buf.clear()   # discard stale window before re-arming
                        ramp_last_w = None
                        ramp_last_t = None
                        state       = "RAMPDOWN"
                        time.sleep(CTRL_STEP)
                        continue

            time.sleep(DETECT_POLL_SECS)

        # ── RAMPDOWN ──────────────────────────────────────────────────────────
        elif state == "RAMPDOWN":
            elapsed   = time.monotonic() - ramp_start
            ramp_frac = max(0.0, 1.0 - elapsed / RAMPDOWN_SECS)
            target_w  = baseline_w + (handoff_w - baseline_w) * ramp_frac

            if _CALIB_AVAILABLE:
                iters = _calib_watts_to_iters(target_w)
            else:
                iters = int(FALLBACK_MAX_ITERS * ramp_frac)
            iters_per_window.value = iters

            abort_reason: str | None = None

            if ramp_last_w is not None and ramp_last_t is not None:
                dt_r = t_now - ramp_last_t
                if dt_r > 0 and (w_now - ramp_last_w) / dt_r >= BACKOFF_THRESHOLD:
                    abort_reason = "backoff"

            if abort_reason is None and w_now <= baseline_w + BASELINE_MARGIN:
                abort_reason = "baseline_reached"

            if abort_reason is None and elapsed >= RAMPDOWN_SECS:
                abort_reason = "normal"

            if abort_reason is not None:
                iters_per_window.value = IDLE_FLOOR_ITERS

                final_w     = rapl.snapshot_watts(window=CALIB_WINDOW)
                actual_secs = round(time.monotonic() - ramp_start, 2)
                print(f"[Event {event_num}] Ramp done ({abort_reason})  "
                      f"init_iters={event_initial_iters:,}  "
                      f"handoff={handoff_w:.1f} W  final≈{final_w:.1f} W  "
                      f"baseline={baseline_w:.1f} W  elapsed={actual_secs:.2f} s")
                _append_event({
                    "event_num":         event_num,
                    "detected_at_s":     round(event_detect_t, 4),
                    "rate_w_per_s":      round(event_rate, 1),
                    "power_at_detect_w": round(event_detect_w, 2),
                    "baseline_w":        round(baseline_w, 2),
                    "handoff_w":         round(handoff_w, 2),
                    "initial_iters":     event_initial_iters,
                    "final_w":           round(final_w, 2),
                    "ramp_duration_s":   actual_secs,
                    "abort_reason":      abort_reason,
                })
                state = "COOLDOWN"
                time.sleep(CTRL_STEP)
                continue

            ramp_last_w = w_now
            ramp_last_t = t_now
            time.sleep(CTRL_STEP)

        # ── COOLDOWN ──────────────────────────────────────────────────────────
        elif state == "COOLDOWN":
            time.sleep(COOLDOWN_SECS)
            deriv_buf.clear()   # discard stale window before re-arming
            state = "IDLE"

    # ── Graceful shutdown ─────────────────────────────────────────────────────
    print("\n[Daemon] Shutting down …")
    iters_per_window.value = 0
    time.sleep(0.05)
    stop_evt.set()
    for w in workers:
        w.join(timeout=3)
    rapl.stop()

    try:
        os.remove(PID_FILE)
    except OSError:
        pass

    _write_samples(rapl.all_samples())
    print(f"[Daemon] Events log → {EVENTS_CSV}")


if __name__ == "__main__":
    main()
